# Generated by Django 3.1.7 on 2021-03-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210303_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['imgpath']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('user', 'imgpath')},
        ),
    ]
