# Generated by Django 3.1.7 on 2021-03-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210330_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='appoved_by',
            new_name='approved_by',
        ),
    ]
