# Generated by Django 3.1.7 on 2021-03-26 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210317_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='userevent',
            name='appoved_by_project_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userevent',
            name='appoved_by_student_advisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userevent',
            name='appoved_by_student_president',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userevent',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventAppovedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.BooleanField(default=False)),
                ('detail', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.userevent')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event'],
            },
        ),
    ]
