# Generated by Django 3.1.7 on 2021-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210330_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
