# Generated by Django 3.1.7 on 2021-03-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_eventappovedlog_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_document', to='api.userregisterevent')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
