# Generated by Django 3.1.7 on 2021-03-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eventdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_document', to='api.userevent'),
        ),
    ]
